[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sclead"
version = "0.1.0"
description = "Single-cell language-model-guided embedding and annotation workflows."
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "anndata",
    "h5py",
    "matplotlib",
    "numpy",
    "pandas",
    "pytorch_lightning==2.5.3",
    "scanpy",
    "scikit_learn",
    "seaborn",
    "torch==2.5.1",
    "transformers==4.55.3",
]

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["sclead"]

# add this section
[tool.setuptools.package-data]
sclead = ["ct_descriptions/*.json"]
